### PR TITLE
Fix installation of custom error handler during context creation in O…

### PR DESCRIPTION
**Pull request by martin-neuhaeusser**
…Caml bindings

This patch fixes a bug detected by valgrind, where a custom error handler
did not get installed correctly.

### CODE REVIEW

**Comment by wintersteiger** [comment]
Thanks for the fix, that looks totally fine. 

It looks like you removed the parameter lists to some functions. I took particular care and invested additional time to add them to every single function, such that there can never be any question about the types being involved (otherwise I was confused, the users were confused, or the system got confused, and sometimes all three of them at the same time). Could you perhaps take those out for now, so that it stays consistent?

**Comment by martin-neuhaeusser** [comment]
Yes, I have removed the last commit 8097fd5.
Usually, type annotations are omitted wherever possible in OCaml. But here they might actually be useful, as they allow to detect errors in the auto-generated Z3native module early and precisely by the OCaml type checker.

**Comment by martin-neuhaeusser** [comment]
I added another patch to the PR that removes the conversion from OCaml lists into arrays.
Instead of doing so, the C layer now processes the arrays directly.
This saves the memory and time needed for allocating and copying these arrays; in fact, the associated costs became visible in our profilings.

**Comment by wintersteiger** [comment]
Awesome, thanks for going to all that trouble! Doing that in the C-layer should definitely have a positive impact on performance. 

Do you have any other items/patches on the OCaml todo-list? If not, do you think we can merge this into master soon?

**Comment by martin-neuhaeusser** [comment]
There is another bugfix in #5 which should make it into master, I guess. 
I will run our benchmarks again with the new OCaml bindings and report back here if everything works well.

Apart from that, I only have two minor issues, which need not be fixed right now, I think.
I include them here only for a future reference.
1. Z3's OCaml API does not follow the convention that the "main" type within a module (e.g. the type expr in module Z3.Expr) has name "t". This has the effect that one cannot use the modules provided by the OCaml API as functor arguments in any of the established OCaml libraries. For example, one cannot construct functorized (and therefore more efficient) sets, maps, weak hash tables, etc. with elements from the OCaml API without writing a (simple) additional wrapper module.
   However, changing the naming would break backwards-compatibility and the whole issue is not a show-stopper. So you have to decide.
2. Whereas Z3 uses hash consing internally, the OCaml values for ASTs are currently not fed through a hash table. Instead, each time an AST is created, its pointer is wrapped into a newly allocated custom block. What I would like to propose for the long term is to look up the pointer in a hash table and to return any existing block wrapping that pointer (if it exists already). This would guarantee a bijection between the custom blocks and the AST pointers and could potentially speed up operations within OCaml. For example, one could use physical equality to test if two expressions are equal without having to go through the C layer.

**Comment by martin-neuhaeusser** [comment]
Hi Christoph,

I ran our benchmarks several times with the bindings, and everything seems to work well. Before you merge it back, please also incorporate #5 which fixes a typo of mine that breaks the debug build of the OCaml bindings.

**Comment by wintersteiger** [comment]
Awesome, thanks for all the work on this! 

Re 1) above: would it work if we added an additional type called t, which is then defined to be the same as expr?

Re 2) sound like a good idea, but there may also be additional overhead in applications that spend a significand portion of their runtime to create/modify lots of exprs. We could make it configurable though, so depending on the application the user can choose which performance profile they prefer.

**Pull request merged**
